name: dazzify
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.5+21

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  bloc:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  flutter_bloc:
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.10.0
  google_maps_flutter_android: ^2.14.11
  google_maps_flutter_platform_interface: ^2.9.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl:
  intl_utils:
  lottie:
  timezone:
  percent_indicator: ^4.2.4
  pinput:
  solar_icons: ^0.0.5
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  syncfusion_flutter_datepicker:
  dio: ^5.7.0
  internet_connection_checker_plus: ^2.5.2
  dartz: ^0.10.1
  get_it: ^8.0.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  http: ^1.2.2
  shimmer: ^3.0.0
  bloc_concurrency:
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  http_parser: any
  photo_view: ^0.15.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  firebase_analytics: ^11.3.6
  flutter_local_notifications: ^18.0.1
  fcm_config: ^3.6.5
  rxdart: ^0.28.0
  url_launcher: ^6.3.1
  flutter_staggered_grid_view: ^0.7.0
  permission_handler: ^11.4.0
  socket_io_client: ^3.0.2
  flutter_swipe_button: ^2.1.3
  image_cropper: ^8.0.2
  device_info_plus: 11.1.1
  restart: ^1.0.0+1
  chewie: ^1.8.5
  webview_flutter: ^4.13.0
  app_links: ^6.3.2
  share_plus: ^10.1.2
  mwidgets:
  pretty_dio_logger: ^1.4.0
  crypto: ^3.0.6
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  smooth_page_indicator:
  package_info_plus:
  skeletonizer:
  flash: ^3.1.1
  responsive_framework: ^1.5.1
  auto_size_text: ^3.0.0
  flutter_meta_sdk: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  json_serializable:
  injectable_generator: ^2.6.2
  restart_app:

flutter:


  uses-material-design: true

  assets:
    - lib/.env
    - assets/images/
    - assets/icons/
    - assets/json/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
flutter_intl:
  enabled: true

#  rm pubspec.lock && \
#  flutter clean && \
#  cd ios && \
#  pod cache clean --all && \
#  cd .. && \
#  flutter pub get && \
#  cd ios && \
#  pod update && \
#  cd ..
# dart run build_runner --delete-conflicting-outputs

# flutter run --flavor=dev --dart-define=env=dev --split-per-abi
# flutter build ipa --flavor=prod --dart-define=env=prod
# flutter build appBundle --flavor=prod --dart-define=env=prod
# flutter build appbundle --flavor=prod --dart-define=env=prod
# flutter build apk --flavor=dev --dart-define=env=dev --split-per-abi
# flutter build apk --flavor=prod --dart-define=env=prod --split-per-abi



#  flutter build appbundle --release --flavor=prod --dart-define=env=prod
#  flutter build ios --config-only --release --flavor=prod --dart-define=env=prod
